name: Build

on: [push, pull_request]

jobs:
  build-windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.18'
      - name: Build
        shell: pwsh
        run: |
          go build -buildmode=c-shared -o obs-studio-plugin.dll
      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: obs-studio-plugin-windows
          path: obs-studio-plugin.dll
